import { v4 as uuid } from "uuid";

import {
  shoe1,
  shoe2,
  shoe3,
  shoe4,
  shoe5,
  shoe6,
  shoe7,
  shoe8,
  jacket1,
  jacket2,
  jacket3,
  jacket4,
  jacket5,
  jacket6,
  jacket7,
  jacket8,
  accessory1,
  accessory2,
  accessory3,
  accessory4,
  accessory5,
  accessory6,
  accessory7,
  accessory8,
} from "../../assets";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: shoe1,
    subtitle: "Soft Trainers",
    brand: "Zara",
    price: "3590",
    categoryName: "shoes",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: shoe2,
    subtitle: "Running Trainers",
    brand: "Zara",
    price: "5990",
    categoryName: "shoes",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "WestSide",
    imgSrc: shoe3,
    subtitle: "Multi-Piece Trainers",
    brand: "Westside",
    price: "3590",
    categoryName: "shoes",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: shoe4,
    subtitle: "MultiColored Running",
    brand: "H&M",
    price: "4590",
    categoryName: "shoes",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: shoe5,
    subtitle: "Retro Monochrome Trainer",
    brand: "H&M",
    price: "2990",
    categoryName: "shoes",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Westside",
    imgSrc: shoe6,
    subtitle: "Contrast Running Trainer",
    brand: "Westside",
    price: "1990",
    categoryName: "shoes",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: shoe7,
    subtitle: "Multipiece Sneaker",
    brand: "Zara",
    price: "3990",
    categoryName: "shoes",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: shoe8,
    subtitle: "Running Trainers With Zip",
    brand: "Zara",
    price: "5990",
    categoryName: "shoes",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: jacket1,
    subtitle: "Hooded Jacket",
    brand: "Zara",
    price: "5990",
    categoryName: "jackets",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: jacket2,
    subtitle: "Jacquard Jacket",
    brand: "Zara",
    price: "5990",
    categoryName: "jackets",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "WestSide",
    imgSrc: jacket3,
    subtitle: "Contrast Patch Jacket",
    brand: "Westside",
    price: "3590",
    categoryName: "jackets",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: jacket4,
    subtitle: "Boat Print Jacket",
    brand: "H&M",
    price: "4590",
    categoryName: "jackets",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: jacket5,
    subtitle: "Bandanna Print Jacket",
    brand: "H&M",
    price: "2990",
    categoryName: "jackets",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Westside",
    imgSrc: jacket6,
    subtitle: "Faux Leather Jacket",
    brand: "Westside",
    price: "6990",
    categoryName: "jackets",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: jacket7,
    subtitle: "Metallic Puffer Jacket",
    brand: "Zara",
    price: "3990",
    categoryName: "jackets",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: jacket8,
    subtitle: "Linen Jacket",
    brand: "Zara",
    price: "5990",
    categoryName: "jackets",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: accessory1,
    subtitle: "Man Gold + Man Silver Perfume",
    brand: "Zara",
    price: "3590",
    categoryName: "accessories",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: accessory2,
    subtitle: "Man Gold Perfume",
    brand: "Zara",
    price: "5990",
    categoryName: "accessories",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "WestSide",
    imgSrc: accessory3,
    subtitle: "Tie with insects",
    brand: "Westside",
    price: "590",
    categoryName: "accessories",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: accessory4,
    subtitle: "Tie with dogs",
    brand: "H&M",
    price: "590",
    categoryName: "accessories",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: accessory5,
    subtitle: "Shearling Belt Bag",
    brand: "H&M",
    price: "2990",
    categoryName: "accessories",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Westside",
    imgSrc: accessory6,
    subtitle: "Flat Cap",
    brand: "Westside",
    price: "1990",
    categoryName: "accessories",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: accessory7,
    subtitle: "Bucket Hat",
    brand: "Zara",
    price: "3990",
    categoryName: "accessories",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Zara",
    imgSrc: accessory8,
    subtitle: "Slogan Cap",
    brand: "Zara",
    price: "5990",
    categoryName: "accessories",
    gender: "men",
    rating: 5,
  },
];
